services:
    folia:
        stdin_open: true
        tty: true
        ports:
            - 25565:25565
        container_name: endkind-folia
        volumes:
            - endkind-folia:/data
        environment:
            - MAX_RAM=3G
            - MINECRAFT_EULA=true
        restart: always
        image: ${DOCKER_NAMESPACE:-endkind}/folia:latest

volumes:
    endkind-folia:
